export const data=[
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
    {
        name:"Temur",
        username:"Tamurbek",
        email:"temuryoldoshev10@gmail.com",
        phone:"916261026"
    },
]